name: 习讯云自动签到

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # 使用 node:10
      - name: use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      # npm install
      - name: 签到日志
        env:
          ACCOUNT: ${{ secrets.Z2002010704 }}
          PASSWORD: ${{ secrets.“Tang2017！” }}
          ADDRESS: ${{ secrets.江苏省常州市金坛区薛埠镇奥托立夫大道1号 }}
          ADDRESS_NAME: ${{ secrets.奥托立夫（江苏）汽车安全零部件有限公司 }}
          LATITUDE: ${{ secrets.31.702695 }}
          LONGITUDE: ${{ secrets.119.354323 }}
          SCHOOL_ID: ${{ secrets.684 }}
          EMAIL: ${{ secrets.EMAIL }}
          CODE: ${{ secrets.CODE }}
          TOKEN: ${{ secrets.1321d1ba05f942b6a3f499354d03436 }}
        run: |
          npm install
          node app.js
